input.buttonsAB.onEvent(ButtonEvent.Click, function () {
  control.runInParallel(function () {
      music.baDing.play()
  })
})
input.buttonA.onEvent(ButtonEvent.Click, function () {
  crickit.motor2.setInverted(true)
  crickit.motor1.setInverted(true)
  crickit.tank(40, 40)
  control.waitMicros(2500000)
  music.setVolume(140)
  music.powerUp.playUntilDone()
  crickit.motor1.stop()
  control.waitMicros(1000000)
  music.magicWand.play()
  light.showAnimation(light.cometAnimation, 1000)
  crickit.tank(40, 40)
  control.waitMicros(1000000)
  crickit.motor2.setInverted(false)
  crickit.tank(60, 60)
  light.showAnimation(light.sparkleAnimation, 2000)
  light.showAnimation(light.colorWipeAnimation, 2000)
  control.waitMicros(4000000)
  crickit.motor1.stop()
  crickit.motor2.stop()
  light.clear()
})
input.buttonB.onEvent(ButtonEvent.Click, function () {
  crickit.motor2.setInverted(false)
  crickit.motor1.setInverted(false)
  crickit.tank(40, 40)
  control.waitMicros(500000)
  music.setVolume(140)
  music.jumpDown.playUntilDone()
  crickit.motor1.stop()
  control.waitMicros(500000)
  music.magicWand.play()
  light.showAnimation(light.rainbowAnimation, 1000)
  crickit.tank(50, 40)
  control.waitMicros(1000000)
  crickit.motor1.stop()
  crickit.motor2.stop()
  light.clear()
})

